version: '3'
services:
  vue-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-app
    volumes:
       - ./app:/usr/src/app
       - /usr/src/app/node_modules
  api-server:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    container_name: api-server
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules